# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomSquare(object):
    def setupUi(self, CustomSquare):
        CustomSquare.setObjectName("CustomSquare")
        CustomSquare.resize(150, 80)
        CustomSquare.setMinimumSize(QtCore.QSize(150, 80))
        CustomSquare.setMaximumSize(QtCore.QSize(150, 80))
        CustomSquare.setStyleSheet("QLineEdit {border-radius:5px; border: 1px solid #dcdcdc;}")
        self.ConfirmCustomZonebutton = QtWidgets.QPushButton(CustomSquare)
        self.ConfirmCustomZonebutton.setGeometry(QtCore.QRect(10, 50, 131, 23))
        self.ConfirmCustomZonebutton.setObjectName("ConfirmCustomZonebutton")
        self.label_CustomSquareOfZone = QtWidgets.QLabel(CustomSquare)
        self.label_CustomSquareOfZone.setGeometry(QtCore.QRect(10, 0, 131, 16))
        self.label_CustomSquareOfZone.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CustomSquareOfZone.setObjectName("label_CustomSquareOfZone")
        self.lineEdit_CustomSquare = QtWidgets.QLineEdit(CustomSquare)
        self.lineEdit_CustomSquare.setGeometry(QtCore.QRect(12, 20, 131, 20))
        self.lineEdit_CustomSquare.setObjectName("lineEdit_CustomSquare")

        self.retranslateUi(CustomSquare)
        QtCore.QMetaObject.connectSlotsByName(CustomSquare)

    def retranslateUi(self, CustomSquare):
        _translate = QtCore.QCoreApplication.translate
        CustomSquare.setWindowTitle(_translate("CustomSquare", "Dialog"))
        self.ConfirmCustomZonebutton.setText(_translate("CustomSquare", "Ок"))
        self.label_CustomSquareOfZone.setText(_translate("CustomSquare", "Площадь зоны"))
